- name: setup gluebuddy.archlinux.org
  hosts: gluebuddy.archlinux.org
  remote_user: root
  roles:
    - { role: common }
    - { role: sshd }
    - { role: root_ssh }
    - { role: borg_client, tags: ["borg"] }
    - { role: sudo }
    - { role: fail2ban }
    - { role: prometheus_exporters }
    - { role: promtail }
    - { role: gluebuddy }
